### ISSUE TITLE
Interpolation changed in DataInterpolations

### ISSUE THREAD

**Issue by phajy** [astro-group-bristol/Gradus.jl#179]
The default value of `extrapolate` in DataInterpolations has been changed to `false`. See https://github.com/SciML/DataInterpolations.jl/pull/194.

This can, in some cases, break Gradus.

Adding `;extrapolate=true)` to all of the `DataInterpolations.LinearInterpolation` calls in the following lines seems to fix the problem.

https://github.com/astro-group-bristol/Gradus.jl/blob/e9e863213a3bd6e67d87178141742d52acc27f98/src/orbits/orbit-solving.jl#L115-L121

I would guess that extrapolations near the edge of the domain are expected. Not sure if this needs to be looked at a bit more?

**Comment by phajy** [comment]
Fixed in https://github.com/astro-group-bristol/Gradus.jl/pull/180

**Comment by fjebaker** [comment]
Thanks for finding the source of this issue. I can see from the CI test suite failing that there are likely a few other places where there was extrapolation happening. I need to step through them and decide whether extrapolating those calculations is actually what we want to do. I think for the orbit solving that should be fine 👍
