### ISSUE TITLE
fov keyword in rendergeodesics

### ISSUE THREAD

**Issue by ben1sheff** [astro-group-bristol/Gradus.jl#182]
Running getting_started.jl has an issue during the rendergeodesics call. Specifically, 

"ERROR: LoadError: Unrecognized keyword arguments found.
The only allowed keyword arguments to `solve` are:
[...]
Unrecognized keyword arguments: [:fov]"

**Comment by fjebaker** [comment]
Hi @ben1sheff thanks for opening this issue! :+1:  For whatever reason that part of the documentation had escaped our test suite, so I have added it to be tracked to make sure it will be kept up to date in the future.

The published documentation should update soon!
