### ISSUE TITLE
Benchmark suite

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/Gradus.jl#30]
As part of our tests, we should also keep a benchmark suite to track the performance of our code, and make sure new changes don't accidentally cause our integration to slow down.

This should have `--math-mode=ieee` and a variety integration tolerances and image sizes to ensure our methods scale well, and don't git the GC too hard (as they have in the past).

**Comment by phajy** [comment]
With regard to GC, I noticed that `lagtransfer` can spend a lot of time no garbage collection. `3533.139993 seconds (292.44 M allocations: 87.741 GiB, 83.50% gc time, 0.02% compilation time)`.

Was thinking of creating a new issue, but this can come under the umbrella of including benchmarking in the tests.
