### ISSUE TITLE
Reduce pre-compilation time

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/Gradus.jl#38]
Takes about two minutes to pre-compile. This should really be reduced, there is no reason for this to be so long.

**Comment by fjebaker** [comment]
Julia 1.9 fixed this for us lol -- down to about 36 seconds. There is no doubt more to be done here, but I might open a new issue to track that when the time comes.

I had a basic play around with SnoopCompile and PrecompilerTools etc., but there is nothing obvious that stands out that we could do. It seems most of the long compilation times come from our dependencies, so maybe using the new "Ext" packages would be a way we could do some of that?

Anyway -- that is for another issue.

**Comment by phajy** [comment]
Ha ha - I like this solution. Just wait and Julia will get better around you :)
