### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/Gradus.jl#76]
Self descriptive

**Comment by phajy** [comment]
The [Covariant radiative transfer](https://astro-group-bristol.github.io/Gradus.jl/dev/examples/examples/#Covariant-radiative-transfer) example isn't working. The documentation is likely lagging behind the code but I couldn't figure it out myself at a quick look - will continue looking.

The code in the documentation produces the following
```
ERROR: TypeError: in keyword argument μ, expected Float64, got a value of type Int64
```

**Comment by fjebaker** [comment]
@phajy yes I am aware of this bug, it was broken in 
- https://github.com/astro-group-bristol/Gradus.jl/commit/3f9024ee43d0527921096ec46d87f80526d94765

The code that fixes it is in master, via
- https://github.com/astro-group-bristol/Gradus.jl/commit/7d77a2c76f3a00efaf4613e92fd9aa8c1fe1e541
- https://github.com/astro-group-bristol/Gradus.jl/commit/fd04487112b74465b00dfde70ed26ce04563ce2a

but the version has not been bumped since, which is why the registry version is still out of date.

I will open an issue about adding the examples to a seperate test-suite though, so that these breaking changes are caught earlier. They were removed to reduce the test runner time, but this isn't the first time an example has broken since that was done, so they should really be added back.
