### ISSUE TITLE
Completely sample 2D transfer functions

### ISSUE THREAD

**Issue by fjebaker** [astro-group-bristol/Gradus.jl#79]
### Discussed in https://github.com/astro-group-bristol/Gradus.jl/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **phajy** February  6, 2023</sup>
I'm trying to run the 2D transfer function example you shared earlier, @fjebaker, but I can't get it to work because I think a few things have changed under the hood in Gradus. The two errors I get are that `getgeodesicpoint not defined` and `radial_sampler not defined`.</div>

Continuing discussion in this issue.

**Comment by phajy** [comment]
Increasing `Nr` and using an `InverseGrid()` did the trick (although `GeometricGrid()` was also fine with increased `Nr`).

**Comment by fjebaker** [comment]
Closing as this seems resolved.
